### ISSUE TITLE
Buttonbeschriftungen in Fensterdialogen sind englisch

### ISSUE THREAD

**Issue by pippcat** [Schachigel/DKV2#101]
Kleinigkeit und überhaupt nicht wichtig, aber es ist mir gerade aufgefallen und ich dachte, ich nehme es als Anlass, hier mal in Kontakt zu kommen:
Die Buttons der Fensterdialoge sind auf englisch und ich frage mich, ob es an der Software oder meinem Betriebssystem liegt?
![image](https://user-images.githubusercontent.com/19587872/223683792-b97d6ed8-153e-4455-a7ce-438a7068fac2.png)

Ich nutze das AppImage unter NixOS, meine locale ist deutsch:
```
[nix-shell:~/Downloads]$ locale
LANG=de_DE.utf8
LC_CTYPE="de_DE.utf8"
LC_NUMERIC="de_DE.utf8"
LC_TIME="de_DE.utf8"
LC_COLLATE="de_DE.utf8"
LC_MONETARY="de_DE.utf8"
LC_MESSAGES="de_DE.utf8"
LC_PAPER="de_DE.utf8"
LC_NAME="de_DE.utf8"
LC_ADDRESS="de_DE.utf8"
LC_TELEPHONE="de_DE.utf8"
LC_MEASUREMENT="de_DE.utf8"
LC_IDENTIFICATION="de_DE.utf8"
LC_ALL=
```

**Comment by Schachigel** [comment]
Hallo,
ob die Texte in deutsch oder englisch erscheinen, hängt davon ab, ob in dem Unterordner mit dem Namen "translations" die deutsche Sprachdatei ("Qt_de.qm") vorhanden ist. Dkv2 versucht diese zu laden. Falls das nicht klappt, ist englisch der voreingestellte Wert. 

Gruß
Holger
