### ISSUE TITLE
Verwaltung Zinssätze mit max. 100.000€ in 12 Monaten

### ISSUE THREAD

**Issue by onestone-42** [Schachigel/DKV2#104]
Mega cooles Tool! Wir überlegen auch mit unserer DK-Verwaltung von Excel umzusteigen. Was uns etwas verwundert hat, war wie die Zinssätze getrackt werden. Die mit max. 20 Anteilen passen soweit, aber bei denen die unter die Regelung "max. 100.000€ in 12 Monaten fallen" verstehen wir nicht ganz wie die getrackt werden sollen. Das Tool bietet ja nur die Möglichkeit die mit einem festen Zeitrahmen anzulegen. Wir werben aber kontinuierlich DKs ein, bis das halt voll ist, aber der Zinssatz kann durchaus länger als ein Jahr offen sein.
Hat es einen bestimmten Grund, dass das nur über einen fixen Zeitraum getrackt wird und nicht über die letzten 12 Monate immer? Siehst du eine Möglichkeit das anzupassen? (Ich hab C++ und Qt Erfahrung, kann mir das also auch selbst anschauen, wenn du mir vielleicht nen Tipp gibst wo im Code das zu finden ist und mir nen eigenen Fork erstellen, wenn das unerwünschte Funktionalität in dem Tool hier ist)
Vielen Dank!

**Comment by Schachigel** [comment]
Hallo,

"Das Tool bietet ja nur die Möglichkeit die mit einem festen Zeitrahmen anzulegen." 
Das stimmt ja nicht. Es gibt den festen Zeitrahmen oder eben die Option "ohne Datum ("fortlaufend"). Nach dem Feedback, das ich bekommen habe, ist letztere wohl inzwischen bei den meisten Projekten als "richtiger" anerkannt. 

Bei dieser Option wird kein fester Zeitrahmen verwendet, sondern aufsummiert wird immer über 12 Monate vor dem (geplanten) nächsten Vertragsabschluss. Schau Dir dazu auch in den Übersichten die beiden "Liste fortlaufender Geldanlage" an. Ich vermute, das ist es, was Du suchst.
Wenn dem so ist, dann schließe diese Anfrage - ansonsten beschreibe mal besser, was Du suchst.

**Comment by onestone-42** [comment]
Danke für die schnelle Antwort! Tut mir leid, das habe ich im Programm übersehen (muss auch zugeben, dass ich mehr auf die Infoseite online geschaut hatte und das im Programm selbst nur überflogen hab.)
