### ISSUE TITLE
Auflistung Verträge - rote Markierung

### ISSUE THREAD

**Issue by onestone-42** [Schachigel/DKV2#105]
In der Liste mit den Verträgen sind ja manche Verträge rot markiert; soweit ich das erkennen kann, sollten das die Verträge sein bei denen ein Kündigungsdatum in der Vergangenheit eingetragen ist.
Allerdings sind bei uns auch eine ganze Menge anderer Verträge rot gefärbt, die kein Kündigungsdatum eingetragen haben, sondern einfach eine Kündigungsfrist von 6 Monaten. Nach einigem hin und her, habe ich festgestellt, dass alle Verträge ab dem 257. der eingetragen ist (habe in die Datenbank selbst reingeschaut und nach der ID sortiert) rot gefärbt sind.
Habe testweise mal DKs in den ersten 256 gelöscht und für jeden den ich lösche, verschwindet bei einem die rote Färbung, sodass es immer die ersten 256 sind, die korrekt dargestellt werden und alle danach sind rot.
Dass das eine 2er Potenz ist, ab der es schief geht hat mich misstrauisch gemacht...
Hast du eine Idee wo ich nach dem Problem weiter suchen könnte? Könnte das im Programm in der Darstellung liegen?

**Comment by Schachigel** [comment]
hm - spontan fällt mir da nichts ein. Schreib mir mal per mail: 
Welches Betriebssystem? Woher hast Du das Executable? Ist es die aktuellste Version? Kannst Du mir ein LOG file und eine depersonalisierte db schicken, mit der ich das Problem sehen kann?
