### ISSUE TITLE
Berücksichtigen von beendeten Verträgen in Übersichten

### ISSUE THREAD

**Issue by onestone-42** [Schachigel/DKV2#107]
Wenn ich die Gesamtsumme der ausgezahlten Zinsen aus der csv-Datei, die bei der Jahresabrechnung erzeugt wird, mit der Übersicht "Ausgezahlte Zinsen pro Jahr" vergleiche, stimmen die Beträge nicht überein. Wenn ich die Zinsen der mittlerweile beendeten Verträge zusammenzähle, komme ich auf die Differenz der beiden Zahlen. Ähnliches Fehlen von bereits beendeten Verträgen erscheint mir auch in den restlichen Übersichten aufzutreten. Mir scheint es, dass beendete Verträge in den Übersichten nicht berücksichtigt werden?
Außerdem scheinen auch in der Übersicht der Anlagen beendete Verträge nicht berücksichtigt zu werden. Dies scheint mir Gefahrenpotential zur Verletzung der 20 Anteile / 100.000 pro Jahr Regelungen zu bieten. (durch das Kündigen eines Vertrages in einem 20er Zinssatz wird ja kein neuer Anteil frei; wenn der aber in der Übersicht nicht angezeigt wird, sieht es so aus als ob ein neuer angenommen werden kann und somit liefe man Gefahr mehr als 20 anzunehmen; genauso bei der 100.000er Regel; falls ein Kredit in einem Sonderfall kürzer als ein Jahr da ist, würde er in der Aufsummierung nach dem Beenden nicht mehr auftauchen und es könnte passieren, dass die 100.000 überschritten werden, da das Programm eine niedrigere Summe anzeigt)
Ist das gewolltes Verhalten?

Programm läuft unter Windows, in der Version 0.20.0.8

**Comment by wipfl** [comment]
In der Tat werden in den Übersichten beendete Verträge nicht berücksichtigt (es wird nur die Datenbanktabelle 'Buchungen', nicht aber 'exBuchungen' abgefragt). Das Problem wurde bei der Erstellung des Jahresabschlusses bereits berücksichtigt, aber noch nicht in die Übersichten übernommen.

**Comment by Schachigel** [comment]
Hallo !
Ich hatte gestern Abend auch d'rauf geschaut: Scheint von Anfang an nicht
mitbedacht worden sein, die beendeten zu berücksichtigen. Wird ein wenig
fummeliges SQL, aber ich werde es in den nächsten Tagen angehen.
Danke fürs Draufschauen!
Gruß
Holger

Am Do., 27. Juli 2023 um 17:49 Uhr schrieb Wilhelm Pflüger <
***@***.***>:

**Comment by Schachigel** [comment]
@wipfl : Bitte schau Dir den jüngsten commit an. Es scheint ja doch mit einem einzigen SQL statement zu gehen - dieses mal nicht ganz so wenig aufwändig :)

**Comment by Schachigel** [comment]
@onestone-42 : kannst Du den jüngsten Commit testen? Ich habe die Ansicht "Ausgezahlte Zinsen"  überarbeitet ... 
https://github.com/Schachigel/DKV2/tree/Schachigel/issue107

**Comment by onestone-42** [comment]
Leider failed der Bulid Prozess bei mir jedes mal.
Habs mit Docker versucht und auch händisch, aber ich kriegs nicht ans laufen.
Wenn du mir ein AppImage oder eine .exe schickst kann ichs testen.

**Comment by Schachigel** [comment]
Könnten wir per e-mail kommunizieren?

Das Image wird bei jedem Commit gebaut. Du musst nur nach den Actions
gucken. Das ist das jüngste:
https://github.com/Schachigel/DKV2/actions/runs/5776900292

Gruß
Holger


Am So., 20. Aug. 2023 um 09:36 Uhr schrieb onestone-42 <
***@***.***>:

**Comment by Schachigel** [comment]
Um die Listen zur Jahresabrechnung wird sich Wilhelm kümmern. Für die anderen Übersichten mache ich getrennte Issues auf. Bitte immer nur ein Thema pro Issue
