### ISSUE TITLE
Zinsmodus (Zinseszins ja/nein) in den Zinsbriefen nennen

### ISSUE THREAD

**Issue by tamaloa** [Schachigel/DKV2#115]
Es wäre toll wenn der Zinsmodus (Zinsen angespart und verzinst / Zinsen angespart aber nicht verzinst) in den jährlichen Zinsbriefen mit genannt wird.

Vor allem um unnötige Nachfragen zu vermeiden (so manche:r DK-Gebende hat ein Jahr später vergessen welche Zinsoption ausgewählt wurde).

Anbieten würde sich der Ort an dem im Template schon die Ausgabe von ` {{#zzAusgesezt}}(ausgesetzt bis Baugenehmigung){{/zzAusgesezt}}` vorgesehen ist (im Screnshot rot umrandet).

 
![Unbenannt](https://github.com/Schachigel/DKV2/assets/118779/0cbfb1cf-2320-474d-a984-98ab8757403a)

(hat natürlich keine hohe Priorität, aber falls wer sowieso etwas an den Templates macht :)

**Comment by Schachigel** [comment]
Diese Möglichkeit besteht heute schon: 
An der von Dir genannten Stelle kann man den Bezeichner {{Zinsmodell}} verwenden. Dieser wird dann beim Erzeugen der PDFs mit "fest", "zinslos", "auszahlend" und "ansparend" ersetzt. Kannst Du das verwenden?

**Comment by tamaloa** [comment]
Hey, danke für deine schnelle Antwort und entschuldige für die späte Rückmeldung.

JA - das ist passend und kann gut verwendet werden.

Danke
