### ISSUE TITLE
Kreditgeber importieren

### ISSUE THREAD

**Issue by Frando** [Schachigel/DKV2#12]
Hi,
ich hätte einen Feature Request: Kreditgeber aus einer CSV-Datei importieren.
Wie sicher viele andere auch haben wir nicht mit DKV2 gestartet, sondern mit einer Excel-Liste. Da sind unsere ca 100 Kreditgeber*innen drin. Die würden wir nun bald von Hand übertragen. Natürlich wäre es schöner, das aus einer CSV zu importieren. Könnte gerne auch sehr basic sein, d.h. z.B. vorgegebene Feldnamen, die irgendwo dokumentiert sind.
Ist das mit wenig Aufwand möglich?
Alternativ: Ich könnte mir auch vorstellen, ein (erstmal externes) Script dafür zu schreiben, das direkt in die sqlite-Datenbank schreibt. Wenn ich es richtig sehe, könnte ich in die Tabellen `Kreditoren` und `Vertraege` schreiben, plus evtl noch die Initialbuchung (Geldeingang) in `Buchungen`. Sollte das funktionieren, oder hat DKV2 da noch andere gespeicherte Sachen oder Referenzen oder ähnliches?
Danke!
Franz

**Comment by Schachigel** [comment]
Einen Import werde ich nicht implementieren. Das geht ganz einfach mit _DbBrowser for sqlite_. Und bei den Kunden sehe ich da auch keine Probleme. Bei Verträgen und Buchungen muss man vlt aufpassen. Die leere Datenbank sollte man sich auf jeden Fall vom Programm erstellen lassen.
Du solltest mal mit Vopor kontakt aufnehmen. Er hat schon 2 Projekte aus der Open Office Lösung "an Bord geholt" und hat dafür einige Python Programme geschrieben.

**Comment by vopor** [comment]
Hi Franz,
Du könntest Dir mal folgendes Script ansehen:
https://github.com/vopor/DkVerwaltungQt/blob/master/importCsvIntoDkV2.py
Das ist dafür gedacht, aus den Daten der OO-Calc-Version von Volker aus Tübingen eine DKV2-Datenbank zu erstellen.
Ist vielleicht eine Ausgangsbasis...
Gruß, Volker

**Comment by Schachigel** [comment]
Ich sehe gerade, dass man auf GibHub ja auf die Benachrichtigungsmails
antworten kann. Sehr schön.
Könnten wir mal "richtig" mailen? Ich hab Deine Aktion aktiviert bekommen,
aber weiß noch nicht, wie ich das Ergebnis an ein Release "binden" kann.
Geht das auch für Mac? Stellt GitHub den Build Rechner?
Gruß
Holger

Am Mo., 3. Mai 2021 um 18:06 Uhr schrieb Franz Heinzmann <
***@***.***>:

**Comment by Frando** [comment]
I wrote a script to import data from a CSV file: https://github.com/Frando/dkv2-import
It's not generic but can be easily adjusted for different spreadsheet layouts. Is there a place to collect third-party resources like this for DKV2? Maybe the GitHub wiki could be enabled for this.
