### ISSUE TITLE
Programmabsturz bei gefilterter Vertragsliste (Linux)

### ISSUE THREAD

**Issue by wipfl** [Schachigel/DKV2#27]
Reproducable: yes
Branch: main
Start program
Go to Verträge / Listen drucken / Vertragstabelle (gefiltert)
Bämm! 
Maybe a necessary data structure is not filled as the list of contracts is not displayed.

**Comment by Schachigel** [comment]
this option should only be available, if the list (with or without filter) was at least once displayed. I changed that accordingly
