### ISSUE TITLE
Lizenz festlegen (specify License)

### ISSUE THREAD

**Issue by tamaloa** [Schachigel/DKV2#4]
Es wäre schön wenn für diese Software allen klar ist unter welcher Lizenz diese genutzt werden darf. 

Toll wäre natürliche eine Open Source Lizenz :)

**Comment by Schachigel** [comment]
DKV2 wird mit der kostenlosen Version von Qt entwickelt. In sofern muss es ebenfalls mit einer "großzügigen" Lizenz weitergegeben werden. GPLv3 ist wohl das Richtige.

**Comment by tamaloa** [comment]
Ja das klingt für mich nach einer sinnvollen Lizenz.
Gut wäre wenn diese direkt im repository enthalten wäre, das macht die Lizenzwahl im Code sofort sichtbar.

Falls dir das passt kannst du gerne den PR mergen.
