### ISSUE TITLE
SegFault after Liste drucken/Zinsbriefe

### ISSUE THREAD

**Issue by wipfl** [Schachigel/DKV2#43]
There is an segmentation fault after printing the interest letters.
It happens in ContractTableModel::setCol13ExtraData() line 43.
Removing updateView() in MainWindow::on_action_menu_contracts_interestLetters_triggered () fixes this.
As this operation doesn't change the data and the view this should be OK.

**Comment by Schachigel** [comment]
Thx for all your testing, that's great!
Hm - there is no problem on windows. If the model is "broken" after the printing, we should find out what the root cause is. Does this always happen? Can you provide a sample data, with which this happens?

**Comment by Schachigel** [comment]
I was able to reproduce now and your change fixed it
