### ISSUE TITLE
No current account value in contract list

### ISSUE THREAD

**Issue by wipfl** [Schachigel/DKV2#47]
There is no column that shows the current account value in the list of contracts - at least for interestless contracts.
If the contract is without interests the column 'Verzinsliches Guthaben' only shows 'Keine Verzinsung'.
Examples:
A contract of 1.000,- at the beginning, but 500,-- has been paid back.
A contract of 1.000,- and the creditor pays extra 500,-- into the same contract.

Possible solutions:
a) The column 'Verzinsliches Guthaben' shows the current account value instead of 'Keine Verzinsung'.
b) An extra column with the account total value to the last booking (sum of bookings of the contract).

**Comment by Schachigel** [comment]
Thank you for reporting the issue!
