### ISSUE TITLE
Behandlung von Auszahlungen

### ISSUE THREAD

**Issue by wipfl** [Schachigel/DKV2#51]
(Ausnahmsweise deutsch, weil mein Finanz-Englisch nicht ausreicht.)
Bei einem Vertrag mit festem Zinsmodus (nicht auszahlend, nicht thesaurierend) wurden zu einem Zeitpunkt x  die aufgelaufenen Zinsen gespendet an einen Dritten - also ausbezahlt.
Das stellt sich jetzt so dar:
1000,- Einzahlung
10,- Zinsen
10,- Zinsen
10,- Zinsen
30,- Auszahlung
Daraufhin zeigt die Vertragstabelle einen verzinslichen Saldo von 970,- Euro.
Das ist doch irgendwie ungerecht...
m.E. müsste es bei 'Ein-/Auszahlung' tatsächlich einen zusätzlichen Buchungsmodus 'Zinsauszahlung' geben, damit sauber zwischen Auszahlung vom eingelegtem Kredit und aufgelaufenen Zinsen unterschieden werden kann.

**Comment by Schachigel** [comment]
Hm - das zeigt die ganze Unsinnigkeit dieser Vertragsform. Ich halte da nicht viel davon. Ich habe sie implementiert, da sie wohl in Projekten gelebt wird.
Zu Deinem Argument: Ich halte es nicht für stichhaltig. 
Die Zinsen sollen lt. Vertrag nicht verzinst werden. Warum sollte sich das durch eine Auszahlung ändern? Würden die Zinsen nach der Auszahlung verzinst, so wäre das ja nichts anderes als ein "simulierter" auszahlender Vertrag. Genau das wollen wir ja nicht - es ist ja "eine andere Vertragsform".
Können wir aber morgen mal besprechen.
