### ISSUE TITLE
Contract list: option to copy eMail / IBAN to clipboard

### ISSUE THREAD

**Issue by wipfl** [Schachigel/DKV2#52]
In the contract list view it would be nice to have an option (e.g. in the context menu) to copy the eMail address or the IBAN number to clipboard.

**Comment by Schachigel** [comment]
In den Listen kannst du jedes Feld anklicken und mit ctrl c kopieren…

Wilhelm Pflüger ***@***.***> schrieb am Do. 10. Feb. 2022 um
19:13:
