### ISSUE TITLE
Zinsberechnung bei auszahlenden Verträgen mit Einzahlung

### ISSUE THREAD

**Issue by Frando** [Schachigel/DKV2#65]
Hallo,

folgende Situation:
Vertrag mit Zinsmodus "auszahlend", eröffnet am z.B. 1.1.2021 mit 1% Zins.
Erste Einzahlung am 1.1.2021 über 1000 Euro.
Zweite Einzahlung (Aufstockung) am 1.7.2021 über 2000 Euro.
Jetzt rechnet DKV2 zeitgleich zur zweiten Einzahlung die bis dahin angefallenen Zinsen an (also hier: 1000 * 1% * halbes Jahr = 5 Euro).
Dann wird bei der Jahresabrechnung der verbleibende Zins als Jahreszins gerechnet und als Auszahlung angegeben. Also hier 3000 EUR * 1% * 6 Monate = 15 Euro.
Es wird dann eine Auszahlung von 15 Euro verbucht (bzw 14,94 weil halbes Jahr minus 1 Tag). Der Gesamtwert des Vertrages steht dann auf 3005 Euro.

Nach unserem Verständnis sollten bei auszahlenden Verträgen die 5 Euro, die im ersten halben Jahr vor der Aufstockung an Zinsen anfielen, ebenfalls ausgezahlt werden. Also Auszahlung in diesem Fall 20 Euro, so dass die Gesamtsumme des Vertrages nach dem Jahreswechsel bei 3000 und nicht bei 3005 steht.

Ist das nachvollziehbar? Sehe ich das richtig, dass es im Moment keine Möglichkeit gibt, dass DKV2 das so rechnet?

Danke und schönen Gruß,
Franz

**Comment by Frando** [comment]
Ich habe versucht, das manuell zu lösen in dem ich eine Auszahlung über 5 Euro am 31.12. hinzufüge. Allerdings funktioniert das auch nicht, da das ja *vor* der Jahresabrechnung erfolgen muss, und dann werden *alle* Zinsen auf den Vertrag aufgeschlagen anstatt als "Jahreszins" als Auszahlung verbucht zu werden.

**Comment by Frando** [comment]
Hier habe ich im Quelltext einen Kommentar dazu gefunden:
https://github.com/Schachigel/DKV2/blob/2cae04fc3ba81e693afeeb96851d33e689a1a416/DKV2/contract.cpp#L452
`    // only annualSettlements can be payed out`
Ist das so? Vielleicht liege ich auch in meinem Verständnis wie die Verträge funktionieren falsch.

**Comment by Schachigel** [comment]
Hallo,
so tief hättest Du garnicht graben müssen ;)
Auf der DKV2 Seite unter "Technische Details" heißt es schon ganz oben:
"

   -

   *Zu aktiven Verträge können Ein- oder Auszahlungen gemacht werden. *
   -

      *Dabei werden der "minimale Vertragswert" und der "minimale
      Auszahlungsbetrag" berücksichtigt: Es können keine Buchungen gemacht
      werden, durch die ein Vertrag oder eine Abbuchung entsteht, die zu klein
      ist.*
      -

      *Zum Zeitpunkt einer Ein- oder Auszahlung wird eine Zinsabrechnung
      durchgeführt. Dieser so errechnete "Zwischenzins" wird - unabhängig vom
      Zinsmodus - immer auf den Vertrag angerechnet.*

"
Also ja - Deine Beobachtung ist korrekt. Der Grund ist ein historischer:
die Ein- und Auszahlungen wurden erst später hinzugefügt - da erschien mir
die Lösung "elegant" genug. Gab auch bisher keine Beschwerden.
Wenn man Deinen Wunsch mit der aktuellen Implementierung umsetzen möchte
ist das hier das, was am nächsten dran ist:
[image: image.png]

Das mit den 6 ct kommt daher, dass man die Auszahlung nicht am gleichen Tag
machen kann, wie die Einzahlung. Ich muss mal darüber nachdenken, ob das
ein Problem wäre, das zu ändern ... oder - um die 10 Euro Zins am
Jahresende zu bekommen:
[image: image.png]

Würde Dir das taugen? Kommt das bei Euch häufiger vor?

Gruß
Holger




Am Fr., 11. März 2022 um 12:21 Uhr schrieb Franz Heinzmann <
***@***.***>:

**Comment by Frando** [comment]
Hi, die Bilder werden nicht angezeigt daher kann ich deinen Vorschlag noch nicht nachvollziehen.

Bislang haben wir 2 verträge mit dieser situation, aber es ist gut möglich dass es noch mehr werden.

**Comment by Schachigel** [comment]
*die Bilder werden nicht angezeigt daher kann ich deinen Vorschlag noch
nicht nachvollziehen.*

Dann schreib doch lieber per Mail.
Gruß
Holger



Franz Heinzmann ***@***.***> schrieb am Sa. 12. März 2022 um
20:13:

**Comment by Schachigel** [comment]
Mit der nächsten Version kann man bei Auszahlenden Verträgen die Zinsen auszahlen lassen, die bei Ein- und Auszahlungen anfallen.
