### ISSUE TITLE
Feedback Anlagen

### ISSUE THREAD

**Issue by Frando** [Schachigel/DKV2#66]
Hi,
ich habe heute die Funktion "Anlagen" ausprobiert. Vielen Dank für die Implementierung!

Wir haben diverse Verträge der Variante "100.000er". Hier ist noch ein Mismatch zwischen der rechtlichen Lage und der Darstellung in DKV2:

* In der Anlagenübersicht wird unter "Summe (alle)" und "Summe (aktive)" jeweils der Nominalwert addiert. Das ist nicht korrekt, es müssten alle Einzahlungen addiert werden. Wir haben mehrere Verträge, die z.B. um 10.000 Euro aufgestockt wurden. Diese Einzahlungen sind Teil der Gesamtsumme der jeweiligen Anlage. Diese Summe darf (nach meinem Verständnis) die 100.000 während eines Jahres nicht überschreiten. Die Anzeige in DKV2 suggeriert hier, dass noch mehr "Platz" ist, als real der Fall.
* Die Funktion "fortlaufend" scheint nicht korrekt zu funktionieren. Wenn ich eine Anlage mit "fortlaufend" statt Start- und Enddatum anlege und anschließend "Verträge automatisch zuordnen" klicke, wird die korrekte Anzahl an Verträgen zugeordnet. Allerdings steht in der Spalte "Anzahl (alle)" 1 (statt, wie korrekt, 18). Ebenfalls wird nur ein Vertrag in der Summenberechnung berücksichtigt. Wenn ich auf Rechtsklick -> Verträge anzeigen klicke werden alle Verträge angezeigt.

**Comment by Schachigel** [comment]
>*In der Anlagenübersicht wird unter "Summe (alle)" und "Summe (aktive)"
jeweils der Nominalwert addiert. Das ist nicht korrekt, es müssten alle
Einzahlungen addiert werden. Wir haben mehrere Verträge, die z.B. um 10.000
Euro aufgestockt wurden. Diese Einzahlungen sind Teil der Gesamtsumme der
jeweiligen Anlage. Diese Summe darf (nach meinem Verständnis) die 100.000
während eines Jahres nicht überschreiten. Die Anzeige in DKV2 suggeriert
hier, dass noch mehr "Platz" ist, als real der Fall.*

Das ist schon adressiert und sieht jetzt so aus (s.u.). Ich muss nur mal
wieder ein neues Release machen...
[image: image.png]
*>Die Funktion "fortlaufend" scheint nicht korrekt zu funktionieren. Wenn
ich eine Anlage mit "fortlaufend" statt Start- und Enddatum anlege und
anschließend "Verträge automatisch zuordnen" klicke, wird die korrekte
Anzahl an Verträgen zugeordnet. Allerdings steht in der Spalte "Anzahl
(alle)" 1 (statt, wie korrekt, 18). Ebenfalls wird nur ein Vertrag in der
Summenberechnung berücksichtigt. Wenn ich auf Rechtsklick -> Verträge
anzeigen klicke werden alle Verträge angezeigt.*
Was meinst Du denn mit der "funktion "fortlaufend"? Sprichst Du von der
Anzeige, die beim Anlegen eines Vertrags über die Anlagen, gemacht wird?
Das ist auch ein bekanntes Problem und wird in der nächsten Version auch
gelöst sein.

Gruß
Holger


Am Mo., 14. März 2022 um 13:09 Uhr schrieb Franz Heinzmann <
***@***.***>:

**Comment by Schachigel** [comment]
Das ist in der nächsten Version gelöst.
