### ISSUE TITLE
Ältere Verträge hinzufügen

### ISSUE THREAD

**Issue by Tomptez** [Schachigel/DKV2#67]
Was ist der beste Weg, bereits sei mehreren Jahren laufende Verträge hinzuzufügen?
Wenn ich einen Vertrag mit Anfangsdatum 1.1.12 eingebe, wirkt es, als müse ich erstmal eine Jahresendabrechnung der letzten 10 Jahre durchführen. Gibt es eine Möglichkeit, den Vertrag auf 1.1.12 zu datieren und direkt den heutigen Wert einzugeben? Oder ist es in dem Fall bessser einfach 1.1.22 als Vertragsdatum einzugeben?

Vielen Dank für die tolle Software!

**Comment by Schachigel** [comment]
Ja - wenn der Vertrag "alt" ist, musst Du alle Jahresabrechnungen machen. Bei thesaurierenden Verträgen gibt es da sicher Rundungsunterschiede - so dass die Werte in der Datenbank mit denen, die Du bisher hattest, auseinanderlaufen. Musst Du ausprobieren.
Die Alternative hast Du ja benannt: Vertrag auf den 1.1. buchen und den Wert incl. angesparter Zinsen angeben.
