### ISSUE TITLE
Report and respect limits for Geldanlagen (100.000er and 20er)

### ISSUE THREAD

**Issue by Frando** [Schachigel/DKV2#7]
Aus dem heutigen Call dieser feature request:

- Jeder Direktkreditvertrag wird einer `Geldanlage` zugeordnet. Eine `Geldanlage` hat einen Zinssatz (der den Zinssatz für den DK-Vertrag bestimmt). Eine *Geldanlage* hat neben dem Zinssatz eine Art/Kategorie, entweder `100.000er` oder `20er` (plus vielleicht noch `andere` oder so).

Dann die relevante Auswertung *je Geldanlage*:

Für `100.000er`: 

- Anzeige des Gesamtvolumens derjenigen Kreditverträge in dieser *Geldanlage*, die zwischen heute und heute vor einem Jahr abgeschlossen wurden. Diese Summe darf 100.000 nicht übersteigen. Anzeigen wieviel noch offen ist bis dahin. 

Für `20er`: 

- Wieviel Kreditverträge existieren in der *Geldanlage*. Limit dafür ist 20. Anzeigen wieviel noch offen ist bis dahin. *Wichtig:* Wenn ein `20er`-Vertrag endet, darf der Counter NICHT reduziert werden. Sondern er darf nur zurück auf 0 gesetzt werden, wenn ALLE Verträge in der Geldanlage beendet sind.

Hilfreiche Extra-Features dazu:

- Beim Anlegen eines neues Kredits je nach gewählter *Geldanlage* eine prominente Warnung anzeigen, wenn eine Grenze (s.o.) der Geldanlage durch den Kredit überschritten würde
- Für `100.00er`: Prognose. Wie sieht der Status der Geldanlage an zukünftigem Tag X aus, wenn sich durch einbehaltene Zinsen die Kreditsumme erhöhen? --> Frühwarnsystem. Evtl die Warnung beim anlegen eines neues Kredites so steuern, dass sie angezeigt wird, wenn mit dem neuen Direktkredit das Ergebnis der Prognose für in einem Jahr die 100.000-Euro-Grenze überschreiten würde
- Für `100.00er`: Audit. Für beliebigen Zeitraum/-punkt prüfen, ob die 100.000er-Grenze für alle `100.000er`-Geldanlagen eingehalten wurde.

**Comment by tamaloa** [comment]
Sinnvoll ist als dritte Kategorie die der `Altverträge` (abgeschlossen vor 1.1.2016).

Beachtet werden muss, dass die oben genannten Limits nur innerhalb der 12-Monats-Frist geprüft werden müssen. Um auf der sicheren Seite zu sein bietet es sich an diese täglich gleitend zu prüfen (dann ist z.B. irrelevant wann der 1. Tag der öffentlichen Bewerbung war).

Für die Einwerbung wäre sinnvoll auf einen kurzen Blick in einer Tabelle zu sehen zu welchen Zinssätzen in den kommenden Monaten noch wieviel Anlagevolumen möglich ist. Das scheint mir einfacher als immer für konkrete Tage eine Vorschau generieren zu müssen und erlaubt schnell einen Überblick. Beispiel:
**Noch mögliches Anlagevolumen (für 100.000€ Regel) bzw. Anzahl DKs (für 20er Regel)**
| Typ     | Zinssatz | 1 Monat (bis 23.3.) | 2 Monaten (bis 23.4.) | 3 Monaten (bis 23.5.) |
|---------|----------|---------|----------|----------|
| 20er    | 1,5 %    | 3 Stück | 4 Stück  | 4 Stück  |
| 100.000 | 2 %      | 34.000€ | 40.000€  | 39.000€  |
| 100.000 | 1,5 %    | 4.000€  | 4.000€   | 4.000€   |

Wichtig wäre hier allerdings ein Mechanismus um bereits vereinbarte DKs zu berücksichtigen. Also DKs die angelegt wurden (mit Zielsumme?) für die aber noch kein Geldeingang verbucht wurde.

**Comment by Schachigel** [comment]
Hi,
meine Vorstellung von dem Feature ist ja jetzt schon eine Weile verfügbar und es gab kein Feedback - also gehe ich davon aus, dass man damit die wesentlichen Probleme lösen kann. Ich weiß, dass es nicht in allen Details dem Vorgeschlagenen entspricht, aber es ist sehr flexibel verwendbar.
Ich schließe diese Anfrage.
