### ISSUE TITLE
Assume people not know what 30/360 and act/act is

### ISSUE THREAD

**Issue by DerZyklop** [Schachigel/DKV2#78]
The interest calculation method screen says DKV2 supports 30/360 and act/act.

Here are two paragraphs that could be added to each option in order to give users a little bit more of a clue what they are doing, if they are just starting with the whole direct loans topic.

### 30/360
Die Deutsche Zinsmethode sieht vor, dass jeder Monat mit 30 Zinstagen und ein gesamtes Jahr mit 360 Zinstagen gerechnet wird.

### act/act
Die taggenaue Zinsmethode sieht vor, dass sowohl die Anzahl der Zinstage also auch die Länge des Basisjahres immer kalendergenau bestimmt wird.

**Comment by DerZyklop** [comment]
PS: Would be nice to get information in this screen if this is a setting that can be changes later or if its fixed.

**Comment by Schachigel** [comment]
Hm - diese Info ist bereits in den "ToolTips" enthalten -wenn man die Maus über den Optionen kurz ruhig hält
