### ISSUE TITLE
Geldeingang bei hohen Direktkrediten auf zweite Nachkommastelle runden

### ISSUE THREAD

**Issue by Tomptez** [Schachigel/DKV2#90]
Ein kleinerer Bug:

Bei Direktkrediten über 10.000 mit zwei Nachkommastellen (also exakten Centbeträgen):
Wenn ich den Geldeingang verbuche, wird auf die Zehnerstelle gerunden und dann bemängelt, dass Kredithöhe und Geld sich nicht decken. Es wäre daher schön, wenn beim Geldeingang bereits automatisch auf die zweite Nachkommastelle gerundet wird (passiert bereits bei direktkrediten unter 10.000)

**Comment by Schachigel** [comment]
danke - ist gefixt (kommt mit nächstem Release)
