### ISSUE TITLE
Falsche Zinsbescheinigung, wenn längst beendete Verträge vorhanden sind

### ISSUE THREAD

**Issue by wipfl** [Schachigel/DKV2#96]
Wenn die Jahreszinsbescheinigungen ausgedruckt werden, dann ist die Summe der ausgezahlten Zinsen falsch, wenn der Kreditor Verträge hat, die schon vor der Zinsperiode beendet wurden.
Der Fehler wurde von Lukas (Solijanka) gemeldet.
Die Verträge müssen gefiltert werden, ob sie evtl. zu jung oder zu alt für die jeweilige Zinsperiode sind.

**Comment by Schachigel** [comment]
repariert in e616bba56b3e86d0c5990a9c11f2ea5da69e0c07
